// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _03_AddFKInUser_DepartmentID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03_AddFKInUser_DepartmentID));
        
        string IMigrationMetadata.Id
        {
            get { return "202010102026484_03_AddFKInUser_DepartmentID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
